modLoader="javafml"
loaderVersion="[41,)"
license="LGPL-3.0-or-later "
issueTrackerURL="https://github.com/lukebemish/lesslazyitems/issues/"
[[mods]]
modId="lesslazyitems"
version="${file.jarVersion}"
displayName="Less Lazy Items"
displayURL="https://github.com/lukebemish/lesslazyitems/"
authors="Luke Bemish" #optional
description='''
Are you tired of items not doing their fair share of the work in item collection systems? Fear no more! With this new,
innovative system, you can zap your items with a wand to make them much more helpful.
'''

[[dependencies.lesslazyitems]]
    modId="forge"
    mandatory=true
    versionRange="[41.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lesslazyitems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
